Repository jsd8-novarex/e-commerce-frontend, pull requests merged in 2024-11, with the labels that each got.

#6 merge aof
  src/App.tsx
  src/components/PaymentPage/PaymentDesktop.tsx
  src/components/PaymentPage/PaymentMobile.tsx
  src/components/TransactionPage/CheckoutDesktop.tsx
  src/components/TransactionPage/CheckoutMobile.tsx
  src/components/productPage/ProductImages.tsx
  src/components/profilePage/ProfileDesktop.tsx
  src/components/profilePage/ProfileMobile.tsx
  src/constraints/SHOWIMAGE_DATA.ts
  src/pages/PaymentPage.tsx
  src/pages/ProductPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/TransactionPage.tsx
Labels: bug

#10 edit merge
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/components/AuthenticationForm.tsx
  src/components/Backdrop.tsx
  src/components/CartSidebar.tsx
  src/components/Layout.tsx
  src/components/ShowcaseSection.tsx
  src/components/TransactionPage/CheckoutMobile.tsx
  src/components/button/EditButton.tsx
  src/components/collections/CollectionsFilterBar.tsx
  src/components/collections/ProductCard.tsx
  src/components/navigation/DesktopLeftMenu.tsx
  src/components/navigation/DesktopRightMenu.tsx
  src/components/navigation/NavigationBar.tsx
  src/components/payment/PaymentDesktop.tsx
  src/components/payment/PaymentMobile.tsx
  src/components/product/ProductDetail.tsx
  src/components/product/ProductImages.tsx
  src/components/productPage/ProductDetail.tsx
  src/components/profile/ProfileDesktop.tsx
  src/components/profile/ProfileMobile.tsx
  src/components/transaction/CheckoutDesktop.tsx
  src/components/transaction/CheckoutMobile.tsx
  src/constraints/COLLECTIONS_FILTER_DATA.ts
  src/constraints/SHOWIMAGE_DATA.ts
  src/helpers/handleErrorApi.ts
  src/helpers/utils.ts
  src/index.css
  src/pages/CollectionsPage.tsx
  src/pages/PaymentPage.tsx
  src/pages/ProductPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SignInAdminPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/TransactionPage.tsx
  tailwind.config.js
Labels: bug

#11 create(earth) test
  src/components/AuthenticationForm.tsx
  src/components/CartSidebar.tsx
  src/components/navigation/NavigationBar.tsx
  src/constraints/PRODUCTS_DATA.ts
  src/constraints/SHOWIMAGE_DATA.ts
  src/index.css
  src/pages/SignInAdminPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
Labels: enhancement

#12 Aof (fix CheckPage,PaymentPage && MockData ProfilePage && Create AdminPage)
  src/App.tsx
  src/components/admin/AdminProductList.tsx
  src/components/button/DeleteButton.tsx
  src/components/payment/PaymentDesktop.tsx
  src/components/payment/PaymentMobile.tsx
  src/components/profile/ProfileDesktop.tsx
  src/components/profile/ProfileMobile.tsx
  src/components/transaction/CheckoutDesktop.tsx
  src/components/transaction/CheckoutMobile.tsx
  src/constraints/PROFILE_DATA.ts
  src/pages/AdminPage.tsx
Labels: bug, enhancement

#14 Mine merge
  src/App.tsx
  src/components/CartSidebar.tsx
  src/constraints/PRODUCT_DATA.ts
  src/pages/AboutUsPage.tsx
Labels: bug

#16 Tum1 merge
  src/components/product/ProductDetail.tsx
  src/constraints/SHOWIMAGE_DATA.ts
  src/pages/ProductPage.tsx
Labels: bug

#17 Earth merge
  src/components/AuthenticationForm.tsx
  src/components/ShowcaseSection.tsx
  src/components/collections/ProductCard.tsx
  src/components/navigation/DesktopLeftMenu.tsx
  src/components/navigation/DesktopRightMenu.tsx
  src/components/navigation/HamburgerMenu.tsx
  src/components/navigation/MobileMenu.tsx
  src/components/navigation/NavigationBar.tsx
  src/constraints/PRODUCTS_DATA.ts
  src/constraints/PRODUCT_DATA_V2.ts
  src/constraints/SHOWCASE_DATA.ts
  src/index.css
  src/pages/CollectionsPage.tsx
  src/pages/SignInAdminPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/store/cartItems.store.ts
Labels: enhancement

#18 Earth merge new format
  src/components/CartSidebar.tsx
  src/components/ShowcaseSection.tsx
  src/components/admin/AdminProductList.tsx
  src/components/button/DeleteButton.tsx
  src/components/navigation/HamburgerMenu.tsx
  src/components/navigation/MobileMenu.tsx
  src/components/navigation/NavigationBar.tsx
  src/components/payment/PaymentDesktop.tsx
  src/components/payment/PaymentMobile.tsx
  src/components/profile/ProfileDesktop.tsx
  src/components/profile/ProfileMobile.tsx
  src/constraints/PRODUCT_DATA.ts
  src/constraints/PROFILE_DATA.ts
  src/index.css
  src/pages/AboutUsPage.tsx
  src/pages/ProductPage.tsx
  src/pages/SignInAdminPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
Labels: bug

#20 Mine
  src/components/CartSidebar.tsx
  src/components/ProductInCart.tsx
  src/components/collections/ProductCard.tsx
  src/components/product/ProductImages.tsx
  src/constraints/PRODUCT_DATA_V2.ts
  src/constraints/SHOWIMAGE_DATA.ts
  src/pages/AboutUsPage.tsx
  src/pages/ProductPage.tsx
  src/store/cartItems.store.ts
  src/store/shoppingCart.store.ts
Labels: enhancement

#22 Earth merge
  src/components/Backdrop.tsx
  src/components/CartSidebar.tsx
  src/components/Layout.tsx
  src/components/button/ScrollToTopButton.tsx
  src/components/navigation/CartButton.tsx
  src/components/navigation/DesktopRightMenu.tsx
  src/components/navigation/HamburgerMenu.tsx
  src/components/navigation/NavigationBar.tsx
  src/helpers/utils.ts
  src/hook/useScrollLock.ts
  src/hook/user/useAuthentication.ts
  src/pages/CollectionsPage.tsx
  src/pages/ProductPage.tsx
  src/pages/SignInPage.tsx
  src/store/scrollLock.store.ts
Labels: bug

#23 fix(earth) : edit format code
  src/components/Backdrop.tsx
  src/components/CartSidebar.tsx
  src/components/Layout.tsx
  src/components/ProductInCart.tsx
  src/components/button/ScrollToTopButton.tsx
  src/components/collections/ProductCard.tsx
  src/components/navigation/DesktopRightMenu.tsx
  src/components/navigation/NavigationBar.tsx
  src/components/product/ProductDetail.tsx
  src/constraints/PRODUCTS_DATA.ts
  src/constraints/PRODUCT_DATA.ts
  src/constraints/PRODUCT_DATA_V2.ts
  src/constraints/SHOWIMAGE_DATA.ts
  src/hook/useScrollLock.ts
  src/pages/CollectionsPage.tsx
  src/pages/HomePage.tsx
  src/pages/SignUpPage.tsx
  src/store/shoppingCart.store.ts
Labels: invalid

#26 Aof
  src/components/payment/PaymentDesktop.tsx
  src/components/payment/PaymentMobile.tsx
  src/components/payment/paymentDesktopcomponents/SummaryD.tsx
  src/components/payment/paymentMobilecomponents/SummaryM.tsx
  src/components/transaction/CheckoutDesktop.tsx
  src/components/transaction/CheckoutMobile.tsx
  src/components/transaction/checkoutDesktopcomponents/SummaryD.tsx
  src/components/transaction/checkoutMobilecomponents/SummaryM.tsx
Labels: documentation

#28 Earth merge
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/components/cartSidebar/CartItemActions.tsx
  src/components/cartSidebar/CartSummary.tsx
  src/components/payment/paymentDesktopcomponents/SummaryD.tsx
  src/components/payment/paymentMobilecomponents/SummaryM.tsx
  src/components/product/ProductDetail.tsx
  src/components/transaction/checkoutDesktopcomponents/SummaryD.tsx
  src/components/transaction/checkoutMobilecomponents/SummaryM.tsx
  src/constraints/NAVIGATION_DATA.ts
  src/constraints/PRODUCT_DATA_V2.ts
  src/constraints/PROFILE_DATA.ts
  src/constraints/SHOWCASE_DATA.ts
  src/constraints/SHOWIMAGE_DATA.ts
  src/hook/useScrollLock.ts
  src/hook/user/useRegistration.ts
  src/index.css
  src/pages/ProductPage.tsx
  src/pages/SignUpPage.tsx
Labels: bug

#29 Earth merge
  .gitignore
  package-lock.json
  src/App.tsx
  src/config/axiosConfig.ts
  src/config/errorFromAPI.ts
  src/config/errorFromAPI.type.ts
  src/helpers/utils.ts
  src/hook/useGetTest.ts
  src/service/getTest.ts
  src/store/getTest.store.ts
  vite.config.ts
Labels: bug, enhancement

#30 Mine
  src/components/AuthenticationForm.tsx
  src/components/cartSidebar/CartSidebar.tsx
  src/components/cartSidebar/ProductInCart.tsx
  src/components/navigation/CartButton.tsx
  src/components/navigation/DesktopRightMenu.tsx
  src/components/navigation/UserButton.tsx
  src/constraints/SHOWCASE_DATA.ts
  src/hook/user/useAuthentication.ts
  src/hook/user/useRegistration.ts
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
Labels: enhancement

#34 Edit(mine/Authen) clean code
  src/components/AuthenticationForm.tsx
Labels: enhancement

#38 Earth merge2
  src/pages/CollectionsPage.tsx
  src/pages/ProductPage.tsx
Labels: bug

#39 fix(earth/ProductPage): edit format
  src/pages/ProductPage.tsx
Labels: bug
