Repository jsd8-novarex/e-commerce-frontend, pull requests merged in 2024-12, with the labels that each got.

#42 Mine
  src/hook/products/useGetAllProduct.ts
  src/hook/products/useGetProductById.ts
  src/hook/products/useGetProductChoice.ts
  src/pages/ProductPage.tsx
  src/service/products/getAllProduct.ts
  src/service/products/getProduct.type.ts
  src/service/products/getProductById.ts
  src/service/products/getProductChoice.ts
  src/store/products/getAllProduct.store.ts
  src/store/products/getProductById.store.ts
  src/store/products/getProductChoice.store.ts
Labels: enhancement

#48 Mine
  src/components/collections/ProductCard.tsx
  src/components/collections/ProductOptions.tsx
  src/components/navigation/DesktopLeftMenu.tsx
  src/hook/products/useGetAllProduct.ts
  src/pages/CollectionsPage.tsx
  src/service/products/getAllProduct.ts
  src/service/products/getProductById.ts
  src/service/products/getProductChoice.ts
  src/store/products/getAllProduct.store.ts
Labels: enhancement

#58 Mine
  src/hook/products/useGetAllProduct.ts
  src/pages/CollectionsPage.tsx
  src/store/products/getAllProduct.store.ts
Labels: bug

#66 Earth merge
  src/App.tsx
  src/components/PrivateRoute.tsx
  src/components/cartSidebar/CartItemActions.tsx
  src/components/cartSidebar/CartSidebar.tsx
  src/components/collections/ProductOptions.tsx
  src/components/navigation/UserButton.tsx
  src/components/product/ProductDetail.tsx
  src/components/product/ProductImages.tsx
  src/config/axiosConfig.ts
  src/hook/user/useAuthentication.ts
  src/pages/ProductPage.tsx
  src/store/cart/postCurrentCart.store.ts
Labels: bug, enhancement

#72 Earth
  src/config/axiosConfig.ts
  src/service/cart/postCompleteCart.ts
  src/service/cart/removeItemFromCart.ts
  src/store/cart/addItemToCart.store.ts
  src/store/cart/cartStore.type.ts
  src/store/cart/postCompleteCart.store.ts
  src/store/cart/removeItemFromCart.store.ts
  src/store/cart/updateItemQuantity.store.ts
Labels: enhancement

#76 Mine
  src/components/collections/CollectionsFilterBar.tsx
  src/components/collections/ProductCard.tsx
  src/components/navigation/MobileMenu.tsx
  src/components/product/ProductDetail.tsx
  src/constraints/NAVIGATION_DATA.ts
  src/pages/CollectionsPage.tsx
  src/pages/ProductPage.tsx
  src/store/products/getAllProduct.store.ts
Labels: enhancement

#77 create(earth/Search)
  src/components/navigation/DesktopLeftMenu.tsx
  src/components/navigation/NavigationBar.tsx
  src/components/search/SearchBar.tsx
Labels: enhancement

#83 Dev
  src/components/collections/CollectionsFilterBar.tsx
  src/components/collections/ProductCard.tsx
  src/components/navigation/DesktopLeftMenu.tsx
  src/components/navigation/MobileMenu.tsx
  src/components/navigation/NavigationBar.tsx
  src/components/payment/PaymentDesktop.tsx
  src/components/payment/PaymentMobile.tsx
  src/components/payment/paymentDesktopcomponents/DeliveryAddressD.tsx
  src/components/payment/paymentMobilecomponents/DeliveryAddressM.tsx
  src/components/product/ProductDetail.tsx
  src/components/profile/profileDesktopcomponents/AddressBook.tsx
  src/components/profile/profileDesktopcomponents/ProfileInformation.tsx
  src/components/profile/profileMobilecomponents/AddressBookM.tsx
  src/components/profile/profileMobilecomponents/ProfileM.tsx
  src/components/search/SearchBar.tsx
  src/components/transaction/checkoutDesktopcomponents/AddressShippingD.tsx
  src/components/transaction/checkoutMobilecomponents/AddressShippingM.tsx
  src/config/axiosConfig.ts
  src/constraints/NAVIGATION_DATA.ts
  src/hook/user/useAuthentication.ts
  src/hook/user/useRegistration.ts
  src/pages/CollectionsPage.tsx
  src/pages/ProductPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/VerifyPaymentPage.tsx
  src/service/cart/postCompleteCart.ts
  src/service/cart/removeItemFromCart.ts
  src/service/paymentService.ts
  src/store/cart/addItemToCart.store.ts
  src/store/cart/cartStore.type.ts
  src/store/cart/postCompleteCart.store.ts
  src/store/cart/removeItemFromCart.store.ts
  src/store/cart/updateItemQuantity.store.ts
  src/store/products/getAllProduct.store.ts
Labels: enhancement
